### ISSUE TITLE
change seat

### ISSUE THREAD

**Issue by YogaSakti** [macbook47/kereto_jowo#1]
rada ribet dichange seatnya mas, kan pas pertama booking itu random seat yang kosong jadi gatau seat awal dapet dimana trus apalagi kalo penumpang lebih dari 1 juga. 

paling enak sih auto booking doang gausah change seat 😅😅

**Comment by spyoff** [comment]
Usage: python kai_backd.py retry_num use_proxy(0 if no, 1 if yes) set_seat(0 if no, 1 if yes) recipe

**Comment by YogaSakti** [comment]
oh iya, gak ngeh sama param terakhir wkwkwk maap maap

**Comment by macbook47** [comment]
syudah ada koq wkwkkw.. kedepan tak bikin yg parameter wis, biar gampang baca nya
